<?php
	include "connect.php";
	checkUser();
	if(isset($_SESSION['userName']))
	{
		if($_SESSION['userName']!="Admin")
		{
			header('Location: index.php');
		}
		else
		{
			if(isset($_POST['cheat'])&&isset($_POST['logo'])&&isset($_POST['pozadina'])&&isset($_POST['obavestenja'])&&isset($_POST['fb'])&&isset($_POST['slagalica_time'])&&isset($_POST['mojbroj_time'])&&isset($_POST['spojnice_time'])&&isset($_POST['skocko_time'])&&isset($_POST['koznazna_time'])&&isset($_POST['asocijacije_time']))
			{
			$cheat=mysql_escape_string($_POST['cheat']);
			$logo=mysql_escape_string($_POST['logo']);
			$pozadina=mysql_escape_string($_POST['pozadina']);
			$obavestenja=mysql_escape_string($_POST['obavestenja']);
			$fb=mysql_escape_string($_POST['fb']);
			$slagalica_time=mysql_escape_string($_POST['slagalica_time']);
			$mojbroj_time=mysql_escape_string($_POST['mojbroj_time']);
			$spojnice_time=mysql_escape_string($_POST['spojnice_time']);
			$skocko_time=mysql_escape_string($_POST['skocko_time']);
			$koznazna_time=mysql_escape_string($_POST['koznazna_time']);
			$asocijacije_time=mysql_escape_string($_POST['asocijacije_time']);
			
			if($cheat=="0"||$cheat=="1")
			{
				SaveSettings("anti-cheat",$cheat);
			}
			if(file_exists($logo))
			{
				SaveSettings("index-logo",$logo);
			}
			if(file_exists($pozadina))
			{
				SaveSettings("pozadina",$pozadina);
			}
			if(is_numeric($obavestenja))
			{
				$br="";
				for($i=0;$i<strlen($obavestenja);$i++)
				{
					if(is_numeric($obavestenja[$i]))
					$br.=$obavestenja[$i];
				}
				SaveSettings("buffer-obavestenja",$br);
			}
			if($fb=="0"||$fb=="1")
			{
				SaveSettings("fb",$fb);
			}
			if(is_numeric($slagalica_time))
			{
				$br="";
				for($i=0;$i<strlen($slagalica_time);$i++)
				{
					if(is_numeric($slagalica_time[$i]))
					$br.=$slagalica_time[$i];
				}
				SaveSettings("slagalica-time",$br);
			}
			if(is_numeric($mojbroj_time))
			{
				$br="";
				for($i=0;$i<strlen($mojbroj_time);$i++)
				{
					if(is_numeric($mojbroj_time[$i]))
					$br.=$mojbroj_time[$i];
				}
				SaveSettings("mojbroj-time",$br);
			}
			if(is_numeric($spojnice_time))
			{
				$br="";
				for($i=0;$i<strlen($spojnice_time);$i++)
				{
					if(is_numeric($spojnice_time[$i]))
					$br.=$spojnice_time[$i];
				}
				SaveSettings("spojnice-time",$br);
			}
			if(is_numeric($skocko_time))
			{
				$br="";
				for($i=0;$i<strlen($skocko_time);$i++)
				{
					if(is_numeric($skocko_time[$i]))
					$br.=$skocko_time[$i];
				}
				SaveSettings("skocko-time",$br);
			}
			if(is_numeric($koznazna_time))
			{
				$br="";
				for($i=0;$i<strlen($koznazna_time);$i++)
				{
					if(is_numeric($koznazna_time[$i]))
					$br.=$koznazna_time[$i];
				}
				SaveSettings("koznazna-time",$br);
			}
			if(is_numeric($asocijacije_time))
			{
				$br="";
				for($i=0;$i<strlen($asocijacije_time);$i++)
				{
					if(is_numeric($asocijacije_time[$i]))
					$br.=$asocijacije_time[$i];
				}
				SaveSettings("asocijacije-time",$br);
			}}
			header("Location: settings_panel.php");
		}
	}
?>